---

- name: continuousop config and operation
  hosts: webservers
  user: vagrant
  sudo: True

  tasks:
    - name: set up local_settings.py
      action: template src=../django/${local_settings_file} dest=${webapps_dir}/${app_name}/django/server/local_settings.py

