---

- name: continuousop config and operation
  hosts: webservers
  user: vagrant
  sudo: True

  tasks:
    - name: set up local_settings.py
      action: template src=../django/${local_settings_file} dest=${webapps_dir}/${app_name}/django/server/local_settings.py

    - name: create supervisor program config
      action: template src=../supervisor/${app_name}.ini dest=/etc/supervisor/${app_name}.ini

  handlers:
    - include: supervisor_handlers.yml

    - name: restart app with supervisor
      action: supervisorctl name=${app_name} state=restarted

