---

- name: top level playbook for local installs
  hosts: all
  user: vagrant
  sudo: True

  vars:
    webapps_dir: /opt
    app_name: continuousop
    http_port: 8000
    server_name: localhost
    local_settings_file: local_settings.vagrant.py


  # Eventually, the playbooks should run as a unique user like "ansible".
  # This task will create the ansible user on the machine for the other scripts
  # to deploy as. Unfortunately, I'm getting error:
  # fatal: [127.0.0.1] => {'msg': 'FAILED: ssh ansible@127.0.0.1:2222 : Private key file is encrypted\nTo connect as a different user, use -u <username>.', 'failed': Tru
  #
  # tasks:
  #   - include: ansible_user.yml user=vagrant

- include: developer_tools.yml
- include: mysql.yml
- include: django.yml
- include: nginx.yml
- include: continuousop.yml

