---

- name: nginx installation
  hosts: webservers
  user: vagrant
  sudo: True

  tasks:
    - name: add nginx ppa
      action: apt_repository repo=ppa:nginx/stable state=present

    - name: install nginx
      action: apt pkg=nginx state=present

    - name: remove default nginx site
      action: file path=/etc/nginx/sites-enabled/default state=absent

    - name: write nginx.conf
      action: template src=../nginx/nginx.conf dest=/etc/nginx/nginx.conf

    - name: ensure log directory
      action: file dest=${webapps_dir}/${app_name}/log state=directory

    - name: create nginx site config
      action: template src=../nginx/site.conf dest=/etc/nginx/sites-available/${app_name}.conf

    - name: link nginx config
      action: file src=/etc/nginx/sites-available/${app_name}.conf dest=/etc/nginx/sites-enabled/${app_name}.conf state=link
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      action: service name=nginx state=restarted

