---

- name: create nginx site config
  action: template src=templates/nginx_${app_name}.conf dest=/etc/nginx/sites-available/${app_name}.conf

- name: link nginx config
  action: file src=/etc/nginx/sites-available/${app_name}.conf dest=/etc/nginx/sites-enabled/${app_name}.conf state=link
  notify:
    - restart nginx

- name: create gunicorn config
  action: template src=templates/gunicorn.conf.py dest=${webapps_dir}/${app_name}/gunicorn.conf.py

- name: create supervisor program config
  action: template src=templates/supervisor_${app_name}.ini dest=/etc/supervisor/${app_name}.ini
  notify:
    - restart supervisor

